version: "3.9"
services:
    project:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./src:/app/src
        env_file:
            - .env
        ports:
            - 3000:3000
        depends_on:
            - database
    database:
        image: postgres:latest
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - ./postgres:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
            interval: 5s
            timeout: 10s
            retries: 5
